// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsideArticle: typeof import('./src/components/AsideArticle.vue')['default']
    GridArticle: typeof import('./src/components/GridArticle.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spotlight: typeof import('./src/components/Spotlight.vue')['default']
  }
}
